repos:
-   repo: https://github.com/ambv/black
    rev: 22.6.0
    hooks:
    - id: black
      language_version: python3.8
-   repo: https://gitlab.com/pycqa/flake8
    rev: '3.9.2'
    hooks:
    - id: flake8
      additional_dependencies: [flake8-bugbear]
      args: [
        "--show-source",
        "--ignore=E203,E266,E501,W503,F403,F401,B008,E712",
        "--max-line-length=100",
        "--max-complexity=18",
        "--select=B,C,E,F,W,T4,B9"]
