# .github/workflows/app.yaml
name: PyTest
on: 
  pull_request:
    branches: 
      - main

jobs:
  test:
    name: "Test"
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Ensure latest pip
      run: |
        python -m pip install --upgrade pip
    - name: Install from repo in the test mode
      run: "pip install -e '.[dev]'"
    - name: Test with pytest
      run: |
        pip install pytest
        pip install pytest-cov
        pytest test/ --doctest-modules --junitxml=junit/test-results.xml --cov=pax/ --cov-report=xml
